const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization,X-GIOAI-Token'};
function handleOptions(r){if(r.method==='OPTIONS')return new Response(null,{status:204,headers:CORS})}
function json(d,s){s=s||200;return new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json'}})}
function encVar(v){var b=[];while(true){var g=v&0x7F;v>>=7;if(v)g|=0x80;b.push(g);if(!v)break}return new Uint8Array(b)}
function proto(parts){var c=[];for(var i=0;i<parts.length;i++){var f=parts[i][0],w=parts[i][1],v=parts[i][2];c.push(encVar((f<<3)|w));if(w===0){c.push(encVar(v))}else if(w===2){if(v instanceof Uint8Array){c.push(encVar(v.length));c.push(v)}else if(Array.isArray(v)){var inner=proto(v);c.push(encVar(inner.length));c.push(inner)}else{var e=new TextEncoder().encode(String(v));c.push(encVar(e.length));c.push(e)}}}var t=0;for(var i=0;i<c.length;i++)t+=c[i].length;var buf=new Uint8Array(t);var o=0;for(var i=0;i<c.length;i++){buf.set(c[i],o);o+=c[i].length}return buf}
async function grpc(tk,ep,parts,sid){sid=sid||'';var p=proto(parts);var h={'Authorization':'Bearer '+tk,'Content-Type':'application/grpc-web+proto','x-grpc-web':'1','x-server-offset':'0','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'};if(sid)h['x-session-id']=sid;var r=await fetch(ep,{method:'POST',headers:h,body:p});if(r.status!==200)return null;return new Uint8Array(await r.arrayBuffer())}
function btoaBytes(bytes){return btoa(Array.from(bytes).map(function(c){return String.fromCharCode(c)}).join(''))}
async function handleRequest(r){
if(r.method==='OPTIONS')return handleOptions(r);
var url=new URL(r.url),path=url.pathname;
if(url.searchParams.has('url')){var target=url.searchParams.get('url');var body=r.method==='POST'?await r.text():null;var h={};r.headers.forEach(function(v,k){h[k]=v});var f=await fetch(target,{method:r.method,headers:h,body:body});var rh={...CORS};f.headers.forEach(function(v,k){if(!['set-cookie','access-control-allow-origin'].includes(k.toLowerCase()))rh[k]=v});return new Response(await f.text(),{status:f.status,headers:rh})}
try{
if(path==='/api/sparx/login'&&r.method==='POST'){var b=await r.json();if(!b.username||!b.password)return json({error:'username and password required'},400);var tokResp=await fetch('https://auth.sparxmaths.uk/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'application/json','Origin':'https://maths.sparx-learning.com','Referer':'https://maths.sparx-learning.com/'},body:new URLSearchParams({client_id:'sparx-maths-sw',hd:b.schoolId||'1',username:b.username,password:b.password,grant_type:'password',scope:'openid profile email'})});if(tokResp.ok){try{var d=await tokResp.json();if(d.access_token)return json({token:d.access_token,session_id:d.session_state||'',username:b.username})}catch(e){}}var params=new URLSearchParams({client_id:'sparx-maths-sw',hd:b.schoolId||'1',response_type:'code',scope:'openid profile email',redirect_uri:'https://maths.sparx-learning.com/oauth2/callback'});var page=await fetch('https://auth.sparxmaths.uk/oauth2/auth?'+params,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'text/html'},redirect:'manual'});var html=await page.text();var csrfMatch=html.match(/name=["']_csrf["'][^>]*value=["']([^"']+)["']/);if(!csrfMatch)return json({error:'Login failed'},401);var csrf=csrfMatch[1];var stateMatch=html.match(/name=["']state["'][^>]*value=["']([^"']+)["']/);var state=stateMatch?stateMatch[1]:'';var loginResp=await fetch('https://auth.sparxmaths.uk/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Origin':'https://auth.sparxmaths.uk'},redirect:'manual',body:new URLSearchParams({_csrf:csrf,state:state,username:b.username,password:b.password})});var location=loginResp.headers.get('Location')||'';var codeMatch=location.match(/[?&]code=([^&#]+)/);if(!codeMatch)return json({error:'Login failed: wrong credentials'},401);var code=codeMatch[1];var tokenResp=await fetch('https://auth.sparxmaths.uk/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'application/json'},body:new URLSearchParams({client_id:'sparx-maths-sw',code:code,grant_type:'authorization_code',redirect_uri:'https://maths.sparx-learning.com/oauth2/callback',hd:b.schoolId||'1'})});if(!tokenResp.ok)return json({error:'Token exchange failed'},401);d=await tokenResp.json();return json({token:d.access_token,session_id:d.session_state||'',username:b.username})}
if(path==='/api/sparx/homeworks'&&r.method==='POST'){b=await r.json();if(!b.token)return json({error:'token required'},400);var raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/GetPackageListForActiveUser',[[1,0,1]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/sparx/tasks'&&r.method==='POST'){b=await r.json();if(!b.token||!b.packageId)return json({error:'token and packageId required'},400);raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/GetTaskList',[[1,0,1],[2,2,[[3,2,b.packageId]]]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/sparx/activity'&&r.method==='POST'){b=await r.json();if(!b.token||!b.packageId)return json({error:'token and packageId required'},400);raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/GetActivity',[[1,0,1],[2,2,[[3,2,b.packageId],[5,0,b.taskIndex||0],[6,2,[[5,0,b.activityId||0]]]]]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/sparx/submit'&&r.method==='POST'){b=await r.json();if(!b.token||!b.packageId||!b.answers)return json({error:'token, packageId, answers required'},400);raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/SubmitAnswer',[[1,0,1],[2,2,[[3,2,b.packageId],[5,0,b.taskIndex||0],[6,2,[[5,0,b.activityId||0]]]]],[3,2,JSON.stringify(b.answers)]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/sparx/bookwork'&&r.method==='POST'){b=await r.json();if(!b.token||!b.packageId||b.answer===undefined)return json({error:'token, packageId, answer required'},400);raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/SubmitBookworkCheck',[[1,0,1],[2,2,[[3,2,b.packageId],[5,0,b.taskIndex||0],[6,2,[[5,0,b.activityId||0]]]]],[3,2,String(b.answer)]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/sparx/regstart'&&r.method==='POST'){b=await r.json();if(!b.token||!b.activityId)return json({error:'token and activityId required'},400);raw=await grpc(b.token,'https://studentapi.api.sparxmaths.uk/sparx.swworker.v1.Sparxweb/RegStart',[[1,0,1],[2,2,[[5,0,b.activityId]]]],b.session_id);return json({raw:raw?btoaBytes(raw):null})}
if(path==='/api/ai/solve'&&r.method==='POST'){b=await r.json();if(!b.question)return json({error:'question required'},400);var gk=env.GEMINI_KEY||'';if(gk){var resp=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key='+gk,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:'Solve this Sparx Maths question. Return ONLY the final numerical answer or simplified expression.\nQuestion: '+b.question}]}]})});d=await resp.json();var answer=(d&&d.candidates&&d.candidates[0]&&d.candidates[0].content&&d.candidates[0].content.parts&&d.candidates[0].content.parts[0]&&d.candidates[0].content.parts[0].text||'').trim();return json({answer:answer,provider:'gemini'})}return json({error:'No AI key configured'},400)}
if(path==='/api/lnut/login'&&r.method==='POST'){b=await r.json();if(!b.username||!b.password)return json({error:'username and password required'},400);var resp=await fetch('https://api.languagenut.com/loginController/attemptLogin?'+new URLSearchParams({username:b.username,pass:b.password,friendlyCaptchaToken:'FAILEDTOKEN'}),{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'application/json','Referer':'https://www.languagenut.com/','Origin':'https://www.languagenut.com'}});if(!resp.ok)return json({error:'Login failed: '+resp.status},401);d=await resp.json();if(!d.newToken)return json({error:'Login failed: no token'},401);return json({token:d.newToken,username:b.username,user:d.user||{},curriculums:d.curriculums||[]})}
if(path==='/api/lnut/homeworks'&&r.method==='POST'){b=await r.json();if(!b.token)return json({error:'token required'},400);resp=await fetch('https://api.languagenut.com/assignmentController/getViewableAll?token='+b.token,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}});return json(await resp.json())}
if(path==='/api/lnut/xp-farm'&&r.method==='POST'){b=await r.json();if(!b.token)return json({error:'token required'},400);var ts=new Date().toISOString().replace('Z','.000Z');resp=await fetch('https://api.languagenut.com/gameDataController/addGameScore',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'},body:new URLSearchParams({correctVocabUids:JSON.stringify(b.correctUids||[]),incorrectVocabUids:JSON.stringify(b.incorrectUids||[]),timeStamp:ts,dontStoreStats:'false',product:'secondary',token:b.token,friendlyCaptchaToken:'FAILEDTOKEN'})});return json(resp.ok?await resp.json():{error:resp.statusText},resp.status)}
if(path==='/api/lnut/vocab'&&r.method==='POST'){b=await r.json();if(!b.token||!b.curriculumUid)return json({error:'token and curriculumUid required'},400);resp=await fetch('https://api.languagenut.com/gameDataController/getGameVocab?curriculumUid='+b.curriculumUid+'&product=secondary&_='+Date.now()+'&token='+b.token,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}});return json(await resp.json())}
if(path==='/api/keys'&&r.method==='GET'){return json({worker:'gioai-v2',platforms:['sparx','languagenut','seneca'],status:'operational',endpoints:['POST /api/sparx/login','POST /api/sparx/homeworks','POST /api/sparx/tasks','POST /api/sparx/activity','POST /api/sparx/submit','POST /api/sparx/bookwork','POST /api/sparx/regstart','POST /api/ai/solve','POST /api/lnut/login','POST /api/lnut/homeworks','POST /api/lnut/xp-farm','POST /api/lnut/vocab']})}
return json({error:'Not found',path:path},404)}catch(e){return json({error:e.message},500)}}
addEventListener('fetch',function(event){event.respondWith(handleRequest(event.request))});
